# -*- coding: utf-8 -*-
"""Semantic_Axis_Projections

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vK9JeyQZAnTv1jNP28IfI0LBE2UUXbPK
"""

!pip install sentence-transformers

#IMPORT

import io
import re
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
from google.colab import files
from sentence_transformers import SentenceTransformer
from scipy.stats import pearsonr, norm
from nltk.tokenize import sent_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.decomposition import PCA
from scipy.stats import wasserstein_distance, zscore
from scipy.stats import gaussian_kde

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("vader_lexicon")

# =========================================================
# SEMANTIC AXES
# Cross-sectional T1 / T2 / ALL
# =========================================================

# =========================================================
# GLOBAL PARAMETERS
# =========================================================
MODEL_NAME = "all-roberta-large-v1"
CI_LEVEL = 0.95

SCALES_TO_USE = ["PHQtot", "CESDtot", "GADtot", "PSWQtot"]

RELIABILITY_SCALES = {
    "PHQtot": 0.79,
    "CESDtot": 0.78,
    "GADtot": 0.82,
    "PSWQtot": 0.80
}

# =========================================================
# INITIALIZE EMBEDDING MODEL
# =========================================================
print("\n[1/7] Initializing embedding model...")
model = SentenceTransformer(MODEL_NAME)

# =========================================================
# GENERAL FUNCTIONS
# =========================================================
def fisher_z_transform(r):
    if pd.isna(r):
        return np.nan
    r = np.clip(r, -0.999999, 0.999999)
    return 0.5 * np.log((1 + r) / (1 - r))


def fisher_z_inverse(z):
    return np.tanh(z)


def correlation_confidence_interval(r, n, confidence=0.95):
    if pd.isna(r) or n is None or n <= 3:
        return np.nan, np.nan

    z = fisher_z_transform(r)
    se = 1 / np.sqrt(n - 3)
    z_crit = norm.ppf(1 - (1 - confidence) / 2)

    return (
        float(fisher_z_inverse(z - z_crit * se)),
        float(fisher_z_inverse(z + z_crit * se))
    )


def disattenuation_partial(r_observed, reliability_scale):
    if pd.isna(r_observed) or pd.isna(reliability_scale) or reliability_scale <= 0:
        return np.nan

    return float(np.clip(r_observed / np.sqrt(reliability_scale), -1.0, 1.0))


def correzione_attenuazione(r_observed, reliability_projection, reliability_scale):
    if (
        pd.isna(r_observed)
        or pd.isna(reliability_projection)
        or pd.isna(reliability_scale)
        or reliability_projection <= 0
        or reliability_scale <= 0
    ):
        return np.nan

    corrected = r_observed / np.sqrt(reliability_projection * reliability_scale)
    return float(np.clip(corrected, -1.0, 1.0))


def parse_time_groups(df, time_col="Time"):
    time_values = (
        df[time_col]
        .astype(str)
        .str.strip()
        .str.upper()
        .str.replace(".0", "", regex=False)
    )

    mask_t1 = time_values.isin(["1", "T1", "TIME1", "BASELINE", "PRE"])
    mask_t2 = time_values.isin(["2", "T2", "TIME2", "FOLLOWUP", "POST"])

    return df[mask_t1].copy(), df[mask_t2].copy()


def make_table_value(r, p, ci_low, ci_high):
    if p < 0.001:
        stars = "***"
    elif p < 0.01:
        stars = "**"
    elif p < 0.05:
        stars = "*"
    else:
        stars = ""

    return f"{r:.2f}{stars} [{ci_low:.2f}, {ci_high:.2f}]"


# =========================================================
# EMBEDDING, AXIS, AND PROJECTION FUNCTIONS
# =========================================================
def get_embedding_dim(model):
    return model.get_embedding_dimension()


def encode_texts_batch(texts, model):
    texts = [str(t) if pd.notna(t) else "" for t in texts]
    valid_mask = [t.strip() and t.lower() != "nan" for t in texts]
    valid_texts = [t for t, ok in zip(texts, valid_mask) if ok]

    dim = get_embedding_dim(model)
    embeddings_all = np.full((len(texts), dim), np.nan)

    if len(valid_texts) > 0:
        valid_embeddings = model.encode(valid_texts, show_progress_bar=False)

        idx = 0
        for i, ok in enumerate(valid_mask):
            if ok:
                embeddings_all[i] = valid_embeddings[idx]
                idx += 1

    return embeddings_all, valid_mask


def calc_axis(pos_items, neg_items, model):
    pos_emb = model.encode(pos_items, show_progress_bar=False)
    neg_emb = model.encode(neg_items, show_progress_bar=False)

    return np.mean(pos_emb, axis=0) - np.mean(neg_emb, axis=0)


def project_and_aggregate(texts, axis_vector, model, aggregation="mean"):
    norm_axis = np.linalg.norm(axis_vector)

    if norm_axis == 0:
        return np.array([np.nan] * len(texts))

    scores = []

    for text in texts:
        text = str(text) if pd.notna(text) else ""
        text = text.strip()

        if not text or text.lower() == "nan":
            scores.append(np.nan)
            continue

        sentences = [s.strip() for s in sent_tokenize(text) if s.strip()]

        if len(sentences) == 0:
            scores.append(np.nan)
            continue

        embeddings = model.encode(sentences, show_progress_bar=False)
        projections = np.dot(embeddings, axis_vector) / norm_axis

        if aggregation == "max":
            score = projections[np.argmax(np.abs(projections))]
        else:
            score = np.mean(projections)

        scores.append(score)

    return np.array(scores)


# =========================================================
# SPLIT-HALF RELIABILITY
# =========================================================
def split_on_internal_capitals(text):
    if not str(text).strip():
        return []

    return [p.strip() for p in re.split(r'(?<!^)(?=\s+[A-Z])', str(text)) if p.strip()]


def split_response_units(text, input_col="", mode="std"):
    text = str(text) if pd.notna(text) else ""
    text = text.strip()

    if not text or text.lower() == "nan":
        return []

    if mode in ["agg_mean", "agg_max"]:
        return [s.strip() for s in sent_tokenize(text) if s.strip()]

    if "Phrase" in input_col or "phrase" in input_col:
        if "\n" in text:
            units = text.split("\n")
        elif ";" in text:
            units = text.split(";")
        elif "|" in text:
            units = text.split("|")
        else:
            units = split_on_internal_capitals(text)

            if len(units) <= 1:
                units = sent_tokenize(text)

            if len(units) <= 1 and "," in text:
                units = text.split(",")

            if len(units) <= 1:
                units = re.split(r"\s+", text)

        return [u.strip() for u in units if u.strip()]

    if "," in text:
        units = text.split(",")
    else:
        units = re.split(r"\s+", text)

    return [u.strip() for u in units if u.strip()]


def calc_split_half(texts, axis_vector, model, mode, input_col=""):
    half1, half2 = [], []

    for text in texts:
        units = split_response_units(text, input_col=input_col, mode=mode)

        if len(units) == 0:
            half1.append("")
            half2.append("")
        else:
            half1.append(" ".join(units[0::2]))
            half2.append(" ".join(units[1::2]))

    norm_axis = np.linalg.norm(axis_vector)

    if norm_axis == 0:
        return np.nan

    if mode in ["agg_mean", "agg_max"] or "Text" in input_col or "text" in input_col:
        agg_type = "mean" if mode == "agg_mean" else "max"

        s1 = project_and_aggregate(
            half1,
            axis_vector,
            model,
            aggregation=agg_type
        )

        s2 = project_and_aggregate(
            half2,
            axis_vector,
            model,
            aggregation=agg_type
        )

    else:
        emb1, vm1 = encode_texts_batch(half1, model)
        emb2, vm2 = encode_texts_batch(half2, model)

        s1 = np.full(len(texts), np.nan)
        s2 = np.full(len(texts), np.nan)

        idx1 = np.where(np.array(vm1))[0]
        idx2 = np.where(np.array(vm2))[0]

        if len(idx1) > 0:
            s1[idx1] = np.dot(emb1[idx1], axis_vector) / norm_axis

        if len(idx2) > 0:
            s2[idx2] = np.dot(emb2[idx2], axis_vector) / norm_axis

    valid = ~np.isnan(s1) & ~np.isnan(s2)

    if valid.sum() > 2:
        r_half, _ = pearsonr(s1[valid], s2[valid])

        if pd.notna(r_half) and r_half > 0:
            return float((2 * r_half) / (1 + r_half))

    return np.nan


# =========================================================
# SEMANTIC AXIS SPECIFICATIONS
# =========================================================
def make_score_specs():
    axes = [
        "DEP_WORDS", "DEP_CESD", "DEP_ZUNG",
        "WOR_WORDS", "WOR_ZUNG", "WOR_STAI"
    ]

    dep_specs = [
        ("depText", "Write text (Mean)", "Dep_Text_Mean", "agg_mean"),
        ("depText", "Write text (Max Abs)", "Dep_Text_MaxAbs", "agg_max"),
        ("depText", "Write text", "Dep_Text_Std", "std"),
        ("depWord", "Write words", "Dep_Word_Std", "std"),
        ("depPhrase", "Write phrases", "Dep_Phrase_Std", "std"),
        ("depSelect", "Select words", "Dep_Select_Std", "std"),
    ]

    wor_specs = [
        ("worText", "Write text (Mean)", "Wor_Text_Mean", "agg_mean"),
        ("worText", "Write text (Max Abs)", "Wor_Text_MaxAbs", "agg_max"),
        ("worText", "Write text", "Wor_Text_Std", "std"),
        ("worWord", "Write words", "Wor_Word_Std", "std"),
        ("worPhrase", "Write phrases", "Wor_Phrase_Std", "std"),
        ("worSelect", "Select words", "Wor_Select_Std", "std"),
    ]

    specs = []

    for axis in axes:
        base_specs = dep_specs if axis.startswith("DEP") else wor_specs

        for input_col, formato, internal_name, mode in base_specs:
            specs.append({
                "Axis": axis,
                "input_col": input_col,
                "Formato": formato,
                "internal_name": internal_name,
                "mode": mode
            })

    return specs


# =========================================================
# CROSS-SECTIONAL SEMANTIC AXIS ANALYSES
# =========================================================
def run_cross_sectional_semantic(
    df_subset,
    subset_name,
    score_specs,
    reliabilities_proiezioni,
    scales
):
    rows = []

    for spec in score_specs:
        axis = spec["Axis"]
        formato = spec["Formato"]
        out_col = f"{axis}__{spec['internal_name']}"

        if out_col not in df_subset.columns:
            continue

        rel_proj = reliabilities_proiezioni.get(out_col, np.nan)

        for scale in scales:
            if scale not in df_subset.columns:
                continue

            mask = df_subset[out_col].notna() & df_subset[scale].notna()
            n = int(mask.sum())

            if n <= 2:
                continue

            # Reverse sign so that higher scores indicate greater symptomatology
            x = -df_subset.loc[mask, out_col].astype(float)
            y = df_subset.loc[mask, scale].astype(float)

            r, p = pearsonr(x, y)
            ci_low, ci_high = correlation_confidence_interval(
                r,
                n,
                confidence=CI_LEVEL
            )

            rel_scale = RELIABILITY_SCALES.get(scale, np.nan)

            rows.append({
                "Subset": subset_name,
                "Analysis_Type": "SEMANTIC_AXIS",
                "Axis": axis,
                "Formato": formato,
                "Scala": scale,
                "N": n,

                "r_pearson": float(r),
                "p_value_analytical": float(p),
                "fisher_z": float(fisher_z_transform(r)),
                "CI_low": ci_low,
                "CI_high": ci_high,

                "reliability_scale": rel_scale,
                "reliability_projection_splithalf": rel_proj,
                "r_disattenuated_partial": disattenuation_partial(r, rel_scale),
                "r_disattenuated_full": correzione_attenuazione(
                    r,
                    rel_proj,
                    rel_scale
                ),

                "Table_value": make_table_value(r, p, ci_low, ci_high)
            })

    return pd.DataFrame(rows)


# =========================================================
# LOAD DATASET
# =========================================================
print("\n[2/7] Loading dataset...")
uploaded = files.upload()

if not uploaded:
    print("No file uploaded.")

else:
    filename = next(iter(uploaded))

    try:
        if filename.endswith(".csv"):
            df_base = pd.read_csv(io.BytesIO(uploaded[filename]))

        elif filename.endswith((".xlsx", ".xls")):
            df_base = pd.read_excel(io.BytesIO(uploaded[filename]))

        else:
            raise ValueError("Unsupported file format. Use CSV or XLSX.")

        print("\nColumns found:")
        print(df_base.columns.tolist())

        # =========================================================
        # DEFINE LEXICONS AND SCALE ITEMS
        # =========================================================
        print("\n[3/7] Defining lexicons...")

        dep_pos_words = [
            "happy", "content", "relaxed", "joyful", "pleased", "satisfied",
            "tired", "peaceful", "active", "cheerful", "excited", "fun",
            "calm", "loving", "hopeful", "upbeat", "blessed", "joy",
            "love", "loved", "optimistic"
        ]

        dep_neg_words = [
            "blue", "sad", "lonely", "stressed", "depressed", "angry",
            "down", "anxious", "unhappy", "worried"
        ]

        wor_pos_words = [
            "hopeful", "calm", "happy", "satisfied", "relaxed", "content",
            "unworried", "peaceful", "confident", "carefree"
        ]

        wor_neg_words = [
            "anxious", "sad", "nervous", "stress", "money", "concerned",
            "anxiety", "worried", "fear", "scared", "bothered", "uneasy"
        ]

        cesd_pos = [
            "I felt that I was just as good as other people.",
            "I felt hopeful about the future.",
            "I was happy.",
            "I enjoyed life."
        ]

        cesd_neg = [
            "I was bothered by things that usually don’t bother me.",
            "I did not feel like eating; my appetite was poor.",
            "I felt that I could not shake off the blues, even with the help from family or friends.",
            "I had trouble keeping my mind on what I was doing.",
            "I felt depressed.",
            "I felt that everything I did was an effort.",
            "I thought my life had been a failure.",
            "I felt fearful.",
            "My sleep was restless.",
            "I talked less than usual.",
            "I felt lonely.",
            "People were unfriendly.",
            "I had crying spells.",
            "I felt sad.",
            "I felt that people disliked me.",
            "I could not get going."
        ]

        zung_dep_pos = [
            "Morning is when I feel the best.",
            "I eat as much as I used to.",
            "I still enjoy sex.",
            "My mind is as clear as it used to be.",
            "I find it easy to do the things I used to.",
            "I feel hopeful about the future.",
            "I find it easy to make decisions.",
            "I feel that I am useful and needed.",
            "My life is pretty full.",
            "I still enjoy the things I used to do."
        ]

        zung_dep_neg = [
            "I feel down-hearted and blue.",
            "I have crying spells or feel like it.",
            "I have trouble sleeping at night.",
            "I notice that I am losing weight.",
            "I have trouble with constipation.",
            "My heart beats faster than usual.",
            "I get tired for no reason.",
            "I am restless and can't keep still.",
            "I am more irritable than usual.",
            "I feel that others would be better off if I were dead."
        ]

        zung_pos = [
            "I feel that everything is all right and nothing bad will happen.",
            "I feel calm and can sit still easily.",
            "I can breathe in and out easily.",
            "My hands are usually dry and warm.",
            "I fall asleep easily and get a good night’s rest."
        ]

        zung_neg = [
            "I feel more nervous and anxious than usual.",
            "I feel afraid for no reason at all.",
            "I get upset easily or feel panicky.",
            "I feel like I’m falling apart and going to pieces.",
            "My arms and legs shake and tremble.",
            "I am bothered by headaches neck and back pain.",
            "I feel weak and get tired easily.",
            "I can feel my heart beating fast.",
            "I am bothered by dizzy spells.",
            "I have fainting spells or feel like it.",
            "I get numbness and tingling in my fingers and toes.",
            "I am bothered by stomach aches or indigestion.",
            "I have to empty my bladder often.",
            "My face gets hot and blushes.",
            "I have nightmares."
        ]

        stai_pos = [
            "I feel calm",
            "I feel secure",
            "I feel at ease",
            "I feel satisfied",
            "I feel comfortable",
            "I feel self-confident",
            "I am relaxed",
            "I feel content",
            "I feel steady",
            "I feel pleasant",
            "I feel satisfied with myself",
            "I feel rested",
            "I am \"calm, cool, and collected\"",
            "I am happy",
            "I make decisions easily",
            "I am content",
            "I am a steady person"
        ]

        stai_neg = [
            "I am tense",
            "I feel strained",
            "I feel upset",
            "I am presently worrying over possible misfortunes",
            "I feel frightened",
            "I feel nervous",
            "I am jittery",
            "I feel indecisive",
            "I am worried",
            "I feel confused",
            "I feel nervous and restless",
            "I wish I could be as happy as others seem to be",
            "I feel like a failure",
            "I feel that difficulties are piling up so that I cannot overcome them",
            "I worry too much over something that really doesn't matter",
            "I have disturbing thoughts",
            "I lack self-confidence",
            "I feel inadequate",
            "Some unimportant thought runs through my mind and bothers me",
            "I take disappointments so keenly that I can't put them out of my mind",
            "I get in a state of tension or turmoil as I think over my recent concerns and interests"
        ]

        # =========================================================
        # BUILD SEMANTIC AXES
        # =========================================================
        print("\n[4/7] Building semantic axes...")

        AXES = {
            "DEP_WORDS": calc_axis(dep_pos_words, dep_neg_words, model),
            "DEP_CESD": calc_axis(cesd_pos, cesd_neg, model),
            "DEP_ZUNG": calc_axis(zung_dep_pos, zung_dep_neg, model),
            "WOR_WORDS": calc_axis(wor_pos_words, wor_neg_words, model),
            "WOR_ZUNG": calc_axis(zung_pos, zung_neg, model),
            "WOR_STAI": calc_axis(stai_pos, stai_neg, model),
        }

        SCORE_SPECS = make_score_specs()

        # =========================================================
        # COMPUTE SEMANTIC SCORES
        # =========================================================
        print("\n[5/7] Computing semantic scores...")

        df_scored = df_base.copy()
        reliabilities_proiezioni = {}

        for spec in SCORE_SPECS:
            axis_name = spec["Axis"]
            input_col = spec["input_col"]
            mode = spec["mode"]
            out_col = f"{axis_name}__{spec['internal_name']}"

            print(f"   -> {out_col}")

            if input_col not in df_scored.columns:
                df_scored[out_col] = np.nan
                reliabilities_proiezioni[out_col] = np.nan
                continue

            axis_vector = AXES[axis_name]
            norm_axis = np.linalg.norm(axis_vector)

            if norm_axis == 0:
                df_scored[out_col] = np.nan
                reliabilities_proiezioni[out_col] = np.nan
                continue

            if mode in ["agg_mean", "agg_max"]:
                agg_type = "mean" if mode == "agg_mean" else "max"

                df_scored[out_col] = project_and_aggregate(
                    df_scored[input_col],
                    axis_vector,
                    model,
                    aggregation=agg_type
                )

            else:
                texts = df_scored[input_col].fillna("").astype(str).tolist()
                embeddings, valid_mask = encode_texts_batch(texts, model)

                scores = np.full(len(texts), np.nan)
                valid_idx = np.where(np.array(valid_mask))[0]

                if len(valid_idx) > 0:
                    scores[valid_idx] = (
                        np.dot(embeddings[valid_idx], axis_vector) / norm_axis
                    )

                df_scored[out_col] = scores

            reliabilities_proiezioni[out_col] = calc_split_half(
                df_scored[input_col].tolist(),
                axis_vector,
                model,
                mode,
                input_col=input_col
            )

        # =========================================================
        # CREATE ALL / T1 / T2 SUBSETS
        # =========================================================
        print("\n[6/7] Preparing ALL / T1 / T2 subsets...")

        if "Time" in df_scored.columns:
            df_t1, df_t2 = parse_time_groups(df_scored, time_col="Time")
        else:
            df_t1 = pd.DataFrame(columns=df_scored.columns)
            df_t2 = pd.DataFrame(columns=df_scored.columns)

        subsets = {
            "ALL": df_scored.copy(),
            "T1": df_t1.copy(),
            "T2": df_t2.copy()
        }

        scales = [s for s in SCALES_TO_USE if s in df_scored.columns]

        print("\nClinical scales found:")
        print(scales)

        # =========================================================
        # RUN CROSS-SECTIONAL ANALYSES
        # =========================================================
        print("\n[7/7] Running cross-sectional Semantic Axis analyses...")

        semantic_results = []

        for subset_name, subset_df in subsets.items():
            if len(subset_df) == 0:
                continue

            print(f"   -> {subset_name}")

            sem = run_cross_sectional_semantic(
                df_subset=subset_df,
                subset_name=subset_name,
                score_specs=SCORE_SPECS,
                reliabilities_proiezioni=reliabilities_proiezioni,
                scales=scales
            )

            if len(sem) > 0:
                semantic_results.append(sem)

        df_semantic_results = (
            pd.concat(semantic_results, ignore_index=True)
            if len(semantic_results) > 0
            else pd.DataFrame()
        )

        # =========================================================
        # CREATE HEATMAP TABLE
        # =========================================================
        heatmap_semantic = pd.DataFrame()

        if len(df_semantic_results) > 0:
            heatmap_semantic = df_semantic_results.pivot_table(
                index=["Subset", "Axis", "Formato"],
                columns="Scala",
                values="r_pearson"
            ).reset_index()

        # =========================================================
        # EXPORT RESULTS
        # =========================================================
        print("\nExporting final Excel file...")

        output_file = "SemanticAxes.xlsx"

        with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

            if len(df_semantic_results) > 0:
                df_semantic_results.to_excel(
                    writer,
                    sheet_name="Semantic_CrossSectional",
                    index=False
                )

            if len(heatmap_semantic) > 0:
                heatmap_semantic.to_excel(
                    writer,
                    sheet_name="Heatmap_Semantic",
                    index=False
                )

            df_scored.to_excel(
                writer,
                sheet_name="Dati_Scoring_Semantic",
                index=False
            )

            subsets["T1"].to_excel(
                writer,
                sheet_name="Data_T1",
                index=False
            )

            subsets["T2"].to_excel(
                writer,
                sheet_name="Data_T2",
                index=False
            )

            subsets["ALL"].to_excel(
                writer,
                sheet_name="Data_ALL",
                index=False
            )

            df_reliability = pd.DataFrame(
                list(RELIABILITY_SCALES.items()),
                columns=["Scala", "Affidabilita"]
            )

            df_reliability.to_excel(
                writer,
                sheet_name="Reliability_Scale",
                index=False
            )

            df_rel_proj = pd.DataFrame(
                list(reliabilities_proiezioni.items()),
                columns=["Projection_Score", "SplitHalf_Reliability"]
            )

            df_rel_proj.to_excel(
                writer,
                sheet_name="Reliability_Proiezioni",
                index=False
            )

        files.download(output_file)

        print("\nANALYSIS COMPLETED SUCCESSFULLY!")
        print(f"Exported file: {output_file}")

    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

# =========================================================
# VADER SENTIMENT ANALYSIS ONLY
# Benchmark baseline on depression / worry texts
# =========================================================

CI_LEVEL = 0.95

RELIABILITY_SCALES = {
    "PHQtot": 0.79,
    "CESDtot": 0.78,
    "GADtot": 0.82,
    "PSWQtot": 0.80
}

sia = SentimentIntensityAnalyzer()


# =========================================================
# GENERAL FUNCTIONS
# =========================================================

def fisher_z_transform(r):
    if pd.isna(r):
        return np.nan

    r = np.clip(r, -0.999999, 0.999999)
    return 0.5 * np.log((1 + r) / (1 - r))


def fisher_z_inverse(z):
    return np.tanh(z)


def correlation_confidence_interval(r, n, confidence=0.95):
    if pd.isna(r) or n is None or n <= 3:
        return np.nan, np.nan

    r = np.clip(r, -0.999999, 0.999999)
    z = fisher_z_transform(r)
    se = 1 / np.sqrt(n - 3)
    z_crit = norm.ppf(1 - (1 - confidence) / 2)

    z_low = z - z_crit * se
    z_high = z + z_crit * se

    return float(fisher_z_inverse(z_low)), float(fisher_z_inverse(z_high))


def disattenuation_partial(r_observed, reliability_scale):
    if pd.isna(r_observed) or pd.isna(reliability_scale) or reliability_scale <= 0:
        return np.nan

    corrected = r_observed / np.sqrt(reliability_scale)
    return float(np.clip(corrected, -1.0, 1.0))


def parse_time_groups(df, time_col="Time"):
    time_values = df[time_col].astype(str).str.strip().str.upper()

    mask_t1 = time_values.isin(["1", "T1", "TIME1"])
    mask_t2 = time_values.isin(["2", "T2", "TIME2"])

    return df[mask_t1].copy(), df[mask_t2].copy()


def split_on_internal_capitals(text):
    if not text.strip():
        return []

    parts = re.split(r'(?<!^)(?=\s+[A-Z])', text)
    return [p.strip() for p in parts if p.strip()]


def split_response_units(text, input_col="", mode="std"):
    t_str = str(text) if pd.notna(text) else ""
    t_str = t_str.strip()

    if not t_str or t_str.lower() == "nan":
        return []

    if mode in ["agg_mean", "agg_max"] or "Text" in input_col:
        units = sent_tokenize(t_str)
        return [u.strip() for u in units if u.strip()]

    if "Phrase" in input_col:
        if "\n" in t_str:
            units = t_str.split("\n")
        elif ";" in t_str:
            units = t_str.split(";")
        elif "|" in t_str:
            units = t_str.split("|")
        else:
            units = split_on_internal_capitals(t_str)

            if len(units) <= 1:
                units = sent_tokenize(t_str)

            if len(units) <= 1 and "," in t_str:
                units = [u.strip() for u in t_str.split(",") if u.strip()]

            if len(units) <= 1:
                units = [u.strip() for u in re.split(r"\s+", t_str) if u.strip()]

        return [u.strip() for u in units if u.strip()]

    if "," in t_str:
        units = t_str.split(",")
    else:
        units = re.split(r"\s+", t_str)

    return [u.strip() for u in units if u.strip()]


def clean_text_basic(text):
    t = str(text) if pd.notna(text) else ""
    t = t.strip()
    t = re.sub(r"\s+", " ", t)
    return t


def prepare_text_for_vader(text, input_col="", mode="std"):
    t = clean_text_basic(text)

    if not t or t.lower() == "nan":
        return ""

    if mode in ["agg_mean", "agg_max"] or "Text" in input_col:
        return t

    units = split_response_units(t, input_col=input_col, mode=mode)

    if len(units) == 0:
        return ""

    return ". ".join(units) + "."


def vader_score_single(text, input_col="", mode="std", analyzer=None):
    if analyzer is None:
        analyzer = sia

    prepared = prepare_text_for_vader(
        text,
        input_col=input_col,
        mode=mode
    )

    if not prepared:
        return {
            "sent_neg": np.nan,
            "sent_neu": np.nan,
            "sent_pos": np.nan,
            "sent_compound": np.nan,
            "sent_distress": np.nan
        }

    scores = analyzer.polarity_scores(prepared)

    return {
        "sent_neg": float(scores["neg"]),
        "sent_neu": float(scores["neu"]),
        "sent_pos": float(scores["pos"]),
        "sent_compound": float(scores["compound"]),
        "sent_distress": float(-scores["compound"])
    }


def sentence_level_sentiment(text, analyzer=None):
    if analyzer is None:
        analyzer = sia

    t = clean_text_basic(text)

    if not t or t.lower() == "nan":
        return {
            "sent_mean": np.nan,
            "sent_maxabs": np.nan
        }

    sents = [s.strip() for s in sent_tokenize(t) if s.strip()]

    if len(sents) == 0:
        return {
            "sent_mean": np.nan,
            "sent_maxabs": np.nan
        }

    vals = []

    for s in sents:
        compound = analyzer.polarity_scores(s)["compound"]
        distress = -compound
        vals.append(distress)

    vals = np.array(vals, dtype=float)

    return {
        "sent_mean": float(np.mean(vals)),
        "sent_maxabs": float(vals[np.argmax(np.abs(vals))])
    }


def run_cross_sectional_sentiment_analysis(
    df_subset,
    subset_name,
    sentiment_specs,
    scales
):
    results = []

    for spec in sentiment_specs:
        formato = spec["Formato"]
        domain = spec["Domain"]
        out_col = spec["internal_name"]

        if out_col not in df_subset.columns:
            continue

        for scale_col in scales:
            if scale_col not in df_subset.columns:
                continue

            mask = df_subset[out_col].notna() & df_subset[scale_col].notna()
            n_obs = int(mask.sum())

            if n_obs <= 2:
                continue

            x = df_subset.loc[mask, out_col].astype(float)
            y = df_subset.loc[mask, scale_col].astype(float)

            r_val, p_val = pearsonr(x, y)
            fisher_z = fisher_z_transform(r_val)

            ci_low, ci_high = correlation_confidence_interval(
                r_val,
                n_obs,
                confidence=CI_LEVEL
            )

            rel_scale = RELIABILITY_SCALES.get(scale_col, np.nan)
            r_dis_partial = disattenuation_partial(r_val, rel_scale)

            results.append({
                "Subset": subset_name,
                "Axis": "SENTIMENT",
                "Domain": domain,
                "Formato": formato,
                "Scala": scale_col,
                "N": n_obs,
                "r_pearson": float(r_val),
                "p_value_analytical": float(p_val),
                "fisher_z": float(fisher_z),
                "reliability_scale": rel_scale,
                "r_disattenuated_partial": r_dis_partial,
                "CI_low": ci_low,
                "CI_high": ci_high,
                "Table_value": (
                    f"{r_val:.2f}*** [{ci_low:.2f}, {ci_high:.2f}]"
                    if p_val < 0.001
                    else f"{r_val:.2f}** [{ci_low:.2f}, {ci_high:.2f}]"
                    if p_val < 0.01
                    else f"{r_val:.2f}* [{ci_low:.2f}, {ci_high:.2f}]"
                    if p_val < 0.05
                    else f"{r_val:.2f} [{ci_low:.2f}, {ci_high:.2f}]"
                )
            })

    return pd.DataFrame(results)


# =========================================================
# LOAD DATASET
# =========================================================

print("\n[2/6] Loading dataset...")

filename = "dataset.xlsx"

df_base = pd.read_excel(filename)

print("Dataset loaded:", filename)
print("Number of rows:", len(df_base))
print("\nColumns found in the dataset:")
print(df_base.columns.tolist())


# =========================================================
# SENTIMENT SPECIFICATIONS
# =========================================================

print("\n[3/6] Defining sentiment specifications...")

SENTIMENT_SPECS = [
    {
        "Domain": "DEPRESSION",
        "input_col": "depText",
        "Formato": "Write text (Mean)",
        "internal_name": "SENT__Dep_Text_Mean",
        "mode": "agg_mean"
    },
    {
        "Domain": "DEPRESSION",
        "input_col": "depText",
        "Formato": "Write text (Max Abs)",
        "internal_name": "SENT__Dep_Text_MaxAbs",
        "mode": "agg_max"
    },
    {
        "Domain": "DEPRESSION",
        "input_col": "depWord",
        "Formato": "Write words",
        "internal_name": "SENT__Dep_Word",
        "mode": "std"
    },
    {
        "Domain": "DEPRESSION",
        "input_col": "depPhrase",
        "Formato": "Write phrases",
        "internal_name": "SENT__Dep_Phrase",
        "mode": "std"
    },
    {
        "Domain": "DEPRESSION",
        "input_col": "depText",
        "Formato": "Write text",
        "internal_name": "SENT__Dep_Text",
        "mode": "std"
    },
    {
        "Domain": "DEPRESSION",
        "input_col": "depSelect",
        "Formato": "Select words",
        "internal_name": "SENT__Dep_Select",
        "mode": "std"
    },

    {
        "Domain": "WORRY",
        "input_col": "worText",
        "Formato": "Write text (Mean)",
        "internal_name": "SENT__Wor_Text_Mean",
        "mode": "agg_mean"
    },
    {
        "Domain": "WORRY",
        "input_col": "worText",
        "Formato": "Write text (Max Abs)",
        "internal_name": "SENT__Wor_Text_MaxAbs",
        "mode": "agg_max"
    },
    {
        "Domain": "WORRY",
        "input_col": "worWord",
        "Formato": "Write words",
        "internal_name": "SENT__Wor_Word",
        "mode": "std"
    },
    {
        "Domain": "WORRY",
        "input_col": "worPhrase",
        "Formato": "Write phrases",
        "internal_name": "SENT__Wor_Phrase",
        "mode": "std"
    },
    {
        "Domain": "WORRY",
        "input_col": "worText",
        "Formato": "Write text",
        "internal_name": "SENT__Wor_Text",
        "mode": "std"
    },
    {
        "Domain": "WORRY",
        "input_col": "worSelect",
        "Formato": "Select words",
        "internal_name": "SENT__Wor_Select",
        "mode": "std"
    }
]


# =========================================================
# COMPUTE SENTIMENT SCORES
# =========================================================

print("\n[4/6] Computing sentiment scores...")

df_scored = df_base.copy()

for spec in SENTIMENT_SPECS:
    input_col = spec["input_col"]
    out_col = spec["internal_name"]
    mode = spec["mode"]

    print(f"   -> {out_col}")

    if input_col not in df_scored.columns:
        df_scored[out_col] = np.nan
        df_scored[f"{out_col}__neg"] = np.nan
        df_scored[f"{out_col}__neu"] = np.nan
        df_scored[f"{out_col}__pos"] = np.nan
        df_scored[f"{out_col}__compound"] = np.nan
        continue

    if mode in ["agg_mean", "agg_max"] and "Text" in input_col:
        tmp = df_scored[input_col].apply(
            lambda x: sentence_level_sentiment(x, analyzer=sia)
        )

        tmp_df = pd.DataFrame(
            list(tmp),
            index=df_scored.index
        )

        if mode == "agg_mean":
            df_scored[out_col] = tmp_df["sent_mean"]
        else:
            df_scored[out_col] = tmp_df["sent_maxabs"]

        df_scored[f"{out_col}__neg"] = np.nan
        df_scored[f"{out_col}__neu"] = np.nan
        df_scored[f"{out_col}__pos"] = np.nan
        df_scored[f"{out_col}__compound"] = np.nan

    else:
        scores = df_scored[input_col].apply(
            lambda x: vader_score_single(
                x,
                input_col=input_col,
                mode=mode,
                analyzer=sia
            )
        )

        df_scores = pd.DataFrame(
            list(scores),
            index=df_scored.index
        )

        df_scored[out_col] = df_scores["sent_distress"]
        df_scored[f"{out_col}__neg"] = df_scores["sent_neg"]
        df_scored[f"{out_col}__neu"] = df_scores["sent_neu"]
        df_scored[f"{out_col}__pos"] = df_scores["sent_pos"]
        df_scored[f"{out_col}__compound"] = df_scores["sent_compound"]


# =========================================================
# CREATE T1 / T2 / ALL SUBSETS
# =========================================================

print("\n[5/6] Preparing T1 / T2 / ALL subsets...")

if "Time" in df_scored.columns:
    df_t1, df_t2 = parse_time_groups(
        df_scored,
        time_col="Time"
    )
else:
    df_t1 = pd.DataFrame(columns=df_scored.columns)
    df_t2 = pd.DataFrame(columns=df_scored.columns)

subsets = {
    "ALL": df_scored.copy(),
    "T1": df_t1.copy(),
    "T2": df_t2.copy()
}

scales = [
    s for s in ["PHQtot", "CESDtot", "GADtot", "PSWQtot"]
    if s in df_scored.columns
]


# =========================================================
# RUN CROSS-SECTIONAL ANALYSES
# =========================================================

print("\n[6/6] Running cross-sectional analyses...")

cross_results = []

for subset_name, subset_df in subsets.items():
    if len(subset_df) == 0:
        continue

    print(f"   -> {subset_name}")

    df_cross = run_cross_sectional_sentiment_analysis(
        df_subset=subset_df,
        subset_name=subset_name,
        sentiment_specs=SENTIMENT_SPECS,
        scales=scales
    )

    if len(df_cross) > 0:
        cross_results.append(df_cross)

df_results = (
    pd.concat(cross_results, ignore_index=True)
    if len(cross_results) > 0
    else pd.DataFrame()
)


# =========================================================
# EXPORT RESULTS
# =========================================================

print("\nExporting Excel file...")

output_file = "Sentiment_Analysis_Benchmark.xlsx"

heatmap_table = pd.DataFrame()

if len(df_results) > 0:
    heatmap_table = df_results.pivot_table(
        index=["Subset", "Domain", "Formato"],
        columns="Scala",
        values="r_pearson"
    ).reset_index()

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    if len(df_results) > 0:
        df_results.to_excel(
            writer,
            sheet_name="CrossSectional",
            index=False
        )

    if len(heatmap_table) > 0:
        heatmap_table.to_excel(
            writer,
            sheet_name="Heatmap_Table",
            index=False
        )

    df_scored.to_excel(
        writer,
        sheet_name="Dati_con_Sentiment",
        index=False
    )

    subsets["T1"].to_excel(
        writer,
        sheet_name="Data_T1",
        index=False
    )

    subsets["T2"].to_excel(
        writer,
        sheet_name="Data_T2",
        index=False
    )

    subsets["ALL"].to_excel(
        writer,
        sheet_name="Data_ALL",
        index=False
    )

files.download(output_file)

print("\nSENTIMENT ANALYSIS SUCCESSFULLY COMPLETED!")
print(f"Exported file: {output_file}")

# =========================================================
# FIGURE 1
# Semantic axis visualization with sentence projections
# =========================================================
MODEL_NAME = "all-roberta-large-v1"

print("[1/3] Caricamento modello...")
model = SentenceTransformer(MODEL_NAME)

# =========================================================
# FUNCTION: SEMANTIC AXIS WITH ORTHOGONAL PROJECTIONS
# =========================================================
def plot_axis_with_sentence_projections(
    pos_words,
    neg_words,
    sentences,
    model,
    output_name,
    max_sentence_len=55
):

    pos_emb = model.encode(pos_words, show_progress_bar=False)
    neg_emb = model.encode(neg_words, show_progress_bar=False)
    sent_emb = model.encode(sentences, show_progress_bar=False)


    pos_center = np.mean(pos_emb, axis=0)
    neg_center = np.mean(neg_emb, axis=0)

    axis_vec_hd = pos_center - neg_center
    axis_norm_hd = np.linalg.norm(axis_vec_hd)

    if axis_norm_hd == 0:
        raise ValueError("The positive and negative centroids coincide.")

    axis_unit_hd = axis_vec_hd / axis_norm_hd
    midpoint_hd = (pos_center + neg_center) / 2


    def project_hd(point):
        v = point - midpoint_hd
        scalar = np.dot(v, axis_unit_hd)
        projected_point = midpoint_hd + scalar * axis_unit_hd
        return projected_point, scalar

    sent_proj_hd = []
    sent_scores = []

    for emb in sent_emb:
        proj, score = project_hd(emb)
        sent_proj_hd.append(proj)
        sent_scores.append(score)

    sent_proj_hd = np.array(sent_proj_hd)
    sent_scores = np.array(sent_scores)

    # PCA
    X_all = np.vstack([
        pos_emb,
        neg_emb,
        sent_emb,
        sent_proj_hd,
        pos_center[None, :],
        neg_center[None, :]
    ])

    pca = PCA(n_components=2)
    X_2d = pca.fit_transform(X_all)

    n_pos = len(pos_words)
    n_neg = len(neg_words)
    n_sent = len(sentences)

    pos_2d = X_2d[:n_pos]
    neg_2d = X_2d[n_pos:n_pos + n_neg]
    sent_2d = X_2d[n_pos + n_neg:n_pos + n_neg + n_sent]

    sent_proj_2d = X_2d[
        n_pos + n_neg + n_sent:
        n_pos + n_neg + 2 * n_sent
    ]

    pos_center_2d = X_2d[-2]
    neg_center_2d = X_2d[-1]


    axis_vec_2d = pos_center_2d - neg_center_2d
    axis_norm_2d = np.linalg.norm(axis_vec_2d)

    if axis_norm_2d == 0:
        raise ValueError("The centroids also coincide in the PCA plane.")

    axis_unit_2d = axis_vec_2d / axis_norm_2d
    midpoint_2d = (pos_center_2d + neg_center_2d) / 2

    all_points_2d = np.vstack([
        pos_2d,
        neg_2d,
        sent_2d,
        sent_proj_2d
    ])

    max_dist = np.max(np.linalg.norm(all_points_2d - midpoint_2d, axis=1))
    line_half_length = max_dist * 1.35

    line_start = midpoint_2d - axis_unit_2d * line_half_length
    line_end = midpoint_2d + axis_unit_2d * line_half_length

    # =====================================================
    # PLOT
    # =====================================================
    plt.figure(figsize=(16, 9))

    plt.scatter(
        pos_2d[:, 0],
        pos_2d[:, 1],
        s=70,
        color="blue",
        alpha=0.20
    )

    for i, word in enumerate(pos_words):
        plt.text(
            pos_2d[i, 0],
            pos_2d[i, 1],
            " " + word,
            fontsize=9,
            color="blue",
            alpha=0.45
        )

    plt.scatter(
        neg_2d[:, 0],
        neg_2d[:, 1],
        s=70,
        color="red",
        alpha=0.20
    )

    for i, word in enumerate(neg_words):
        plt.text(
            neg_2d[i, 0],
            neg_2d[i, 1],
            " " + word,
            fontsize=9,
            color="red",
            alpha=0.45
        )


    plt.plot(
        [line_start[0], midpoint_2d[0]],
        [line_start[1], midpoint_2d[1]],
        linestyle="--",
        linewidth=2.8,
        color="red"
    )


    plt.plot(
        [midpoint_2d[0], line_end[0]],
        [midpoint_2d[1], line_end[1]],
        linestyle="--",
        linewidth=2.8,
        color="blue"
    )


    plt.scatter(
        sent_2d[:, 0],
        sent_2d[:, 1],
        s=130,
        color="purple",
        marker="D"
    )

    plt.scatter(
        sent_proj_2d[:, 0],
        sent_proj_2d[:, 1],
        s=120,
        color="black",
        marker="D"
    )

    for i, sentence in enumerate(sentences):

        plt.plot(
            [sent_2d[i, 0], sent_proj_2d[i, 0]],
            [sent_2d[i, 1], sent_proj_2d[i, 1]],
            color="gray",
            linestyle=":",
            linewidth=1.5
        )

        short_sentence = sentence

        if len(short_sentence) > max_sentence_len:
            short_sentence = short_sentence[:max_sentence_len] + "..."

        plt.text(
            sent_2d[i, 0] + 0.01,
            sent_2d[i, 1] + 0.01,
            f"{short_sentence}",
            fontsize=9,
            color="purple"
        )


    plt.grid(False)
    plt.axis("off")

    plt.tight_layout()


    plt.savefig(
        output_name,
        dpi=300,
        format="tiff",
        bbox_inches="tight"
    )

    plt.show()


    df_scores = pd.DataFrame({
        "Sentence_ID": [f"S{i+1}" for i in range(len(sentences))],
        "Sentence": sentences,
        "Projection_score": sent_scores
    }).sort_values("Projection_score")

    print(f"Grafico salvato come: {output_name}")
    return df_scores


# =========================================================
# WORRY
# =========================================================
wor_pos_words = [
    "hopeful", "calm", "happy", "satisfied", "relaxed",
    "content", "unworried", "peaceful", "confident", "carefree"
]

wor_neg_words = [
    "anxious", "sad", "nervous", "stress", "money",
    "concerned", "anxiety", "worried", "fear",
    "scared", "bothered", "uneasy"
]

sentences_worry = [
    "I feel nervous all the time and I cannot stop worrying.",
    "I am scared about the future and many things worry me.",
    "There is a lot of stress in my life right now.",
    "I feel calm and in control of my life.",
    "Most days I feel peaceful and relaxed.",
    "I am happy with how things are going.",
    "Sometimes I worry, but I try to stay calm."
]

print("[2/3] Creo grafico worry...")

df_worry_scores = plot_axis_with_sentence_projections(
    pos_words=wor_pos_words,
    neg_words=wor_neg_words,
    sentences=sentences_worry,
    model=model,
    output_name="FIGURE 1.tiff"
)

display(df_worry_scores)

# FIGURE 2

# =========================================================
# 1. LOAD DATA
# =========================================================
file_path = "SemanticAxes.xlsx"

df = pd.read_excel(file_path)

# =========================================================
# 2. SELECT RELEVANT COLUMNS
# =========================================================
df = df[[
    "Subset",
    "Formato",
    "Axis",
    "Scala",
    "r_pearson",
    "r_disattenuated_partial",
    "r_disattenuated_full"
]].copy()

format_order = [
    "Select words",
    "Write phrases",
    "Write words",
    "Write text",
    "Write text (Max Abs)",
    "Write text (Mean)"
]

type_order = ["Raw", "Partial", "Split-half"]

dep_axes = ["DEP_CESD", "DEP_WORDS", "DEP_ZUNG"]
wor_axes = ["WOR_STAI", "WOR_WORDS", "WOR_ZUNG"]

# =========================================================
# 3. PREPARE LONG-FORM DATA
# =========================================================
def prepare_subset_long(data, subset_name):

    sub = data[data["Subset"] == subset_name].copy()

    df_long = sub.melt(
        id_vars=["Subset", "Formato", "Axis", "Scala"],
        value_vars=[
            "r_pearson",
            "r_disattenuated_partial",
            "r_disattenuated_full"
        ],
        var_name="Type",
        value_name="Correlation"
    )

    df_long["Type"] = df_long["Type"].replace({
        "r_pearson": "Raw",
        "r_disattenuated_partial": "Partial",
        "r_disattenuated_full": "Split-half"
    })

    df_long["Formato"] = pd.Categorical(
        df_long["Formato"],
        categories=format_order,
        ordered=True
    )

    df_long["Type"] = pd.Categorical(
        df_long["Type"],
        categories=type_order,
        ordered=True
    )

    return df_long


# =========================================================
# 4. COMPUTE THE MEAN ACROSS THE THREE SEMANTIC AXES
# =========================================================
def aggregate_three_axes(data, scales_list, axes_list):

    sub = data[
        (data["Scala"].isin(scales_list)) &
        (data["Axis"].isin(axes_list))
    ].copy()

    sub["Axis"] = pd.Categorical(
        sub["Axis"],
        categories=axes_list,
        ordered=True
    )

    avg = (
        sub.sort_values(["Formato", "Scala", "Type", "Axis"])
        .groupby(["Formato", "Scala", "Type"], observed=True)
        .agg(
            mean_corr=("Correlation", "mean"),
            n_axes=("Correlation", "size")
        )
        .reset_index()
    )

    avg = avg[avg["n_axes"] == 3].copy()

    avg["Scala_label"] = avg["Scala"].replace({
        "CESDtot": "CESD",
        "PHQtot": "PHQ",
        "GADtot": "GAD",
        "PSWQtot": "PSWQ"
    })

    avg["RowLabel"] = (
        avg["Formato"].astype(str)
        + " | "
        + avg["Scala_label"].astype(str)
    )

    return avg


# =========================================================
# 5. PREPARE DATA FOR VISUALIZATION
# =========================================================
df_long = prepare_subset_long(df, "ALL")

avg_dep = aggregate_three_axes(
    data=df_long,
    scales_list=["CESDtot", "PHQtot"],
    axes_list=dep_axes
)

avg_wor = aggregate_three_axes(
    data=df_long,
    scales_list=["GADtot", "PSWQtot"],
    axes_list=wor_axes
)

# =========================================================
# 6. CREATE HEATMAP MATRICES
# =========================================================
heat_dep = avg_dep.pivot_table(
    index="RowLabel",
    columns="Type",
    values="mean_corr",
    aggfunc="first"
)

heat_wor = avg_wor.pivot_table(
    index="RowLabel",
    columns="Type",
    values="mean_corr",
    aggfunc="first"
)

# =========================================================
# 7. DEFINE ROW ORDER
# =========================================================
dep_row_order = []

for fmt in format_order:
    for scale in ["CESDtot", "PHQtot"]:
        scale_label = scale.replace("tot", "")
        dep_row_order.append(f"{fmt} | {scale_label}")

wor_row_order = []

for fmt in format_order:
    for scale in ["GADtot", "PSWQtot"]:
        scale_label = scale.replace("tot", "")
        wor_row_order.append(f"{fmt} | {scale_label}")

heat_dep = heat_dep.reindex(
    [r for r in dep_row_order if r in heat_dep.index]
)

heat_wor = heat_wor.reindex(
    [r for r in wor_row_order if r in heat_wor.index]
)

# =========================================================
# 8. CREATE COMBINED FIGURE (PANELS A AND B)
# =========================================================
fig, axes = plt.subplots(
    1,
    2,
    figsize=(16, 11)
)

# =========================================================
# PANEL A — DEPRESSION
# =========================================================
ax = axes[0]

im1 = ax.imshow(
    heat_dep.values,
    aspect="auto",
    vmin=0.35,
    vmax=1.0,
    cmap="Blues"
)

ax.set_xticks(range(len(heat_dep.columns)))

ax.set_xticklabels(
    heat_dep.columns,
    fontsize=12
)

ax.set_yticks(range(len(heat_dep.index)))

ax.set_yticklabels(
    heat_dep.index,
    fontsize=11
)

for i in range(heat_dep.shape[0]):
    for j in range(heat_dep.shape[1]):

        val = heat_dep.iloc[i, j]

        if pd.notna(val):

            ax.text(
                j,
                i,
                f"{val:.2f}".replace("0.", "."),
                ha="center",
                va="center",
                fontsize=13
            )

# Panel label
ax.text(
    -0.18,
    1.03,
    "A",
    transform=ax.transAxes,
    fontsize=24,
    fontweight="bold"
)

# =========================================================
# PANEL B — WORRY
# =========================================================
ax = axes[1]

im2 = ax.imshow(
    heat_wor.values,
    aspect="auto",
    vmin=0.35,
    vmax=1.0,
    cmap="Blues"
)

ax.set_xticks(range(len(heat_wor.columns)))

ax.set_xticklabels(
    heat_wor.columns,
    fontsize=12
)

ax.set_yticks(range(len(heat_wor.index)))

ax.set_yticklabels(
    heat_wor.index,
    fontsize=11
)

for i in range(heat_wor.shape[0]):
    for j in range(heat_wor.shape[1]):

        val = heat_wor.iloc[i, j]

        if pd.notna(val):

            ax.text(
                j,
                i,
                f"{val:.2f}".replace("0.", "."),
                ha="center",
                va="center",
                fontsize=13
            )

# Panel label
ax.text(
    -0.18,
    1.03,
    "B",
    transform=ax.transAxes,
    fontsize=24,
    fontweight="bold"
)

# =========================================================
# ADD A SHARED COLORBAR OUTSIDE THE PANELS
# =========================================================

# Create extra space on the right-hand side
fig.subplots_adjust(
    right=0.84,
    wspace=0.55
)

# Define an external axis for the shared colorbar
cbar_ax = fig.add_axes([
    0.88,   # horizontal position
    0.15,   # bottom position
    0.018,  # width
    0.70    # height
])

# Shared colorbar
cbar = fig.colorbar(
    im2,
    cax=cbar_ax
)

cbar.set_label(
    "Correlation",
    fontsize=13
)

cbar.ax.tick_params(
    labelsize=11
)

# =========================================================
# SAVE HIGH-RESOLUTION TIFF FIGURE
# =========================================================
output_name = "FIGURE 2.tiff"

plt.savefig(
    output_name,
    dpi=300,
    format="tiff",
    bbox_inches="tight"
)

plt.show()

print(f"Figure saved as: {output_name}")

#WASSERSTEIN DISTANCE + FIGURE 3


filename = "SemanticAxes.xlsx"

df_scored = pd.read_excel(filename, sheet_name="Dati_Scoring_Semantic")
df_old_results = pd.read_excel(filename, sheet_name="Semantic_CrossSectional")

RANDOM_STATE = 42
CI_LEVEL = 0.95
N_BOOT_WD = 2000
N_PERM_WD = 2000
WD_EQ_THRESHOLD = 0.20

FORMAT_TO_INTERNAL = {
    "Write text (Mean)": "Text_Mean",
    "Write text (Max Abs)": "Text_MaxAbs",
    "Write text": "Text_Std",
    "Write words": "Word_Std",
    "Write phrases": "Phrase_Std",
    "Select words": "Select_Std",
}

def safe_standardize_np(a):
    a = np.asarray(a, dtype=float)
    sd = np.std(a, ddof=1)
    if len(a) < 2 or pd.isna(sd) or sd == 0:
        return np.full(len(a), np.nan)
    return (a - np.mean(a)) / sd

def get_score_col(df, axis_name, formato):
    suffix = FORMAT_TO_INTERNAL.get(formato)
    candidates = [
        c for c in df.columns
        if c.startswith(axis_name + "__") and c.endswith(suffix)
    ]
    return candidates[0] if candidates else None

def filter_subset(df, subset):
    if subset == "ALL" or "Time" not in df.columns:
        return df.copy()

    t = (
        df["Time"].astype(str)
        .str.strip()
        .str.upper()
        .str.replace(".0", "", regex=False)
    )

    if subset == "T1":
        return df[t.isin(["1", "T1", "TIME1", "BASELINE", "PRE"])].copy()
    if subset == "T2":
        return df[t.isin(["2", "T2", "TIME2", "FOLLOWUP", "POST"])].copy()

    return df.copy()

def bootstrap_wasserstein_ci(x, y, n_boot=N_BOOT_WD):
    rng = np.random.default_rng(RANDOM_STATE)

    x = pd.Series(x).astype(float)
    y = pd.Series(y).astype(float)
    mask = x.notna() & y.notna()
    x = x.loc[mask].values
    y = y.loc[mask].values

    n = len(x)
    if n < 10:
        return np.nan, np.nan, np.nan, np.nan

    vals = []

    for _ in range(n_boot):
        idx = rng.choice(np.arange(n), size=n, replace=True)
        xb = safe_standardize_np(x[idx])
        yb = safe_standardize_np(y[idx])

        if not np.isnan(xb).all() and not np.isnan(yb).all():
            vals.append(wasserstein_distance(xb, yb))

    vals = np.asarray(vals)

    return (
        float(np.mean(vals)),
        float(np.percentile(vals, 2.5)),
        float(np.percentile(vals, 97.5)),
        float(np.std(vals, ddof=1))
    )

def permutation_wasserstein_test(x, y, n_perm=N_PERM_WD):
    rng = np.random.default_rng(RANDOM_STATE)

    x = pd.Series(x).astype(float)
    y = pd.Series(y).astype(float)
    mask = x.notna() & y.notna()
    x = x.loc[mask].values
    y = y.loc[mask].values

    if len(x) < 10 or len(y) < 10:
        return np.nan, np.nan, np.nan

    xz = safe_standardize_np(x)
    yz = safe_standardize_np(y)

    wd_obs = wasserstein_distance(xz, yz)

    pooled = np.concatenate([xz, yz])
    n_x = len(xz)

    null = []

    for _ in range(n_perm):
        p = rng.permutation(pooled)
        xp = safe_standardize_np(p[:n_x])
        yp = safe_standardize_np(p[n_x:])
        null.append(wasserstein_distance(xp, yp))

    null = np.asarray(null)

    p_value = (np.sum(null >= wd_obs) + 1) / (len(null) + 1)
    z_wd = (wd_obs - np.mean(null)) / np.std(null, ddof=1)

    return float(p_value), float(z_wd), float(np.mean(null))

def classify_similarity(ci_low, ci_high):
    if pd.isna(ci_low) or pd.isna(ci_high):
        return "insufficient_data"
    if ci_high < WD_EQ_THRESHOLD:
        return "distributionally_similar"
    if ci_low > WD_EQ_THRESHOLD:
        return "distributionally_different"
    return "uncertain"

rows = []

for _, row in df_old_results.iterrows():
    subset = row["Subset"]
    axis = row["Axis"]
    formato = row["Formato"]
    scale = row["Scala"]

    df_use = filter_subset(df_scored, subset)
    score_col = get_score_col(df_use, axis, formato)

    if score_col is None or scale not in df_use.columns:
        continue

    x = -pd.to_numeric(df_use[score_col], errors="coerce")
    y = pd.to_numeric(df_use[scale], errors="coerce")

    mask = x.notna() & y.notna()
    x = x.loc[mask].values
    y = y.loc[mask].values

    if len(x) < 10:
        continue

    xz = safe_standardize_np(x)
    yz = safe_standardize_np(y)

    wd_z = wasserstein_distance(xz, yz)

    boot_mean, ci_low, ci_high, boot_se = bootstrap_wasserstein_ci(x, y)
    perm_p, perm_z, perm_null_mean = permutation_wasserstein_test(x, y)

    new_row = row.to_dict()
    new_row.update({
        "WD_z_new": wd_z,
        "WD_z_boot_mean": boot_mean,
        "WD_z_CI_low": ci_low,
        "WD_z_CI_high": ci_high,
        "WD_z_boot_SE": boot_se,
        "WD_perm_p_difference": perm_p,
        "WD_perm_z": perm_z,
        "WD_perm_null_mean": perm_null_mean,
        "WD_similarity_class": classify_similarity(ci_low, ci_high),
    })

    rows.append(new_row)

df_wd_inference = pd.DataFrame(rows)

wd_summary = (
    df_wd_inference
    .groupby(["Subset", "Axis", "Formato"], as_index=False)
    .agg(
        mean_WD_z=("WD_z_new", "mean"),
        mean_WD_CI_low=("WD_z_CI_low", "mean"),
        mean_WD_CI_high=("WD_z_CI_high", "mean"),
        mean_abs_r=("r_pearson", lambda x: np.nanmean(np.abs(x))),
        n_tests=("WD_z_new", "count"),
        n_distributionally_similar=("WD_similarity_class", lambda x: int(np.sum(pd.Series(x) == "distributionally_similar"))),
        n_distributionally_different=("WD_similarity_class", lambda x: int(np.sum(pd.Series(x) == "distributionally_different"))),
        n_uncertain=("WD_similarity_class", lambda x: int(np.sum(pd.Series(x) == "uncertain"))),
    )
)

output_file = "WD_Inference_From_Precomputed_Scores.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    df_wd_inference.to_excel(writer, sheet_name="WD_Inference", index=False)
    wd_summary.to_excel(writer, sheet_name="WD_Summary", index=False)

files.download(output_file)
print("Completato:", output_file)


# FIGURE 3

df_scored = pd.read_excel(
    "SemanticAxes.xlsx",
    sheet_name="Dati_Scoring_Semantic"
)

print("Loading file: WD_Inference_From_Precomputed_Scores.xlsx")
file_wd = "WD_Inference_From_Precomputed_Scores.xlsx"

df_wd = pd.read_excel(
    file_wd,
    sheet_name="WD_Inference"
)

# ======================================================
# PARAMETERS
# ======================================================
TOP_N = 6

FORMAT_TO_INTERNAL = {
    "Write text (Mean)": "Text_Mean",
    "Write text (Max Abs)": "Text_MaxAbs",
    "Write text": "Text_Std",
    "Write words": "Word_Std",
    "Write phrases": "Phrase_Std",
    "Select words": "Select_Std",
}

# ======================================================
# FUNCTIONS
# ======================================================
def safe_zscore_np(x):
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]

    if len(x) < 2:
        return np.array([])

    sd = np.std(x, ddof=1)

    if sd == 0:
        return np.array([])

    return (x - np.mean(x)) / sd


def get_score_col(df_scored, axis_name, formato):
    suffix = FORMAT_TO_INTERNAL.get(formato)

    if suffix is None:
        return None

    candidates = [
        c for c in df_scored.columns
        if c.startswith(axis_name + "__") and c.endswith(suffix)
    ]

    return candidates[0] if len(candidates) > 0 else None


def filter_subset(df, subset="ALL"):
    if subset == "ALL" or "Time" not in df.columns:
        return df.copy()

    time_values = (
        df["Time"]
        .astype(str)
        .str.strip()
        .str.upper()
        .str.replace(".0", "", regex=False)
    )

    if subset == "T1":
        return df[
            time_values.isin(["1", "T1", "TIME1", "BASELINE", "PRE"])
        ].copy()

    if subset == "T2":
        return df[
            time_values.isin(["2", "T2", "TIME2", "FOLLOWUP", "POST"])
        ].copy()

    return df.copy()


def density_plot(ax, xz, yz):
    grid_min = min(np.min(xz), np.min(yz)) - 0.5
    grid_max = max(np.max(xz), np.max(yz)) + 0.5
    grid = np.linspace(grid_min, grid_max, 400)

    try:
        kde_x = gaussian_kde(xz)
        kde_y = gaussian_kde(yz)

        ax.plot(
            grid,
            kde_x(grid),
            linewidth=2,
            label="AI scores"
        )

        ax.fill_between(
            grid,
            kde_x(grid),
            alpha=0.25
        )

        ax.plot(
            grid,
            kde_y(grid),
            linewidth=2,
            label="Clinical scores"
        )

        ax.fill_between(
            grid,
            kde_y(grid),
            alpha=0.25
        )

    except Exception:
        ax.hist(
            xz,
            bins=20,
            density=True,
            alpha=0.30,
            label="AI scores"
        )

        ax.hist(
            yz,
            bins=20,
            density=True,
            alpha=0.30,
            label="Clinical scores"
        )


def get_top_wd(df_wd, construct, subset, top_n=6):
    if construct == "DEP":
        clinical_scales = ["PHQtot", "CESDtot"]

        temp = df_wd[
            (df_wd["Subset"] == subset) &
            (df_wd["Axis"].str.startswith("DEP")) &
            (df_wd["Scala"].isin(clinical_scales))
        ].copy()

    else:
        clinical_scales = ["GADtot", "PSWQtot"]

        temp = df_wd[
            (df_wd["Subset"] == subset) &
            (df_wd["Axis"].str.startswith("WOR")) &
            (df_wd["Scala"].isin(clinical_scales))
        ].copy()

    top = (
        temp.sort_values(
            ["WD_z_new", "r_pearson"],
            ascending=[True, False]
        )
        .head(top_n)
        .reset_index(drop=True)
    )

    return top


def plot_dep_wor_top6_single_image(df_scored, df_wd, subset="ALL", top_n=6):

    df_use = filter_subset(df_scored, subset=subset)

    top_dep = get_top_wd(df_wd, "DEP", subset, top_n)
    top_wor = get_top_wd(df_wd, "WOR", subset, top_n)

    top_dep["Construct"] = "DEP"
    top_wor["Construct"] = "WOR"

    top_all = pd.concat(
        [top_dep, top_wor],
        ignore_index=True
    )

    fig, axes = plt.subplots(
        nrows=4,
        ncols=3,
        figsize=(18, 18)
    )

    axes = axes.flatten()

    for i, row in top_all.iterrows():
        ax = axes[i]

        axis_name = row["Axis"]
        formato = row["Formato"]
        scale = row["Scala"]
        scale_display = str(scale).replace("tot", "")

        score_col = get_score_col(
            df_use,
            axis_name,
            formato
        )

        if score_col is None or scale not in df_use.columns:
            ax.axis("off")
            continue

        x = -pd.to_numeric(
            df_use[score_col],
            errors="coerce"
        )

        y = pd.to_numeric(
            df_use[scale],
            errors="coerce"
        )

        mask = x.notna() & y.notna()

        x = x.loc[mask].values
        y = y.loc[mask].values

        xz = safe_zscore_np(x)
        yz = safe_zscore_np(y)

        if len(xz) < 5 or len(yz) < 5:
            ax.axis("off")
            continue

        density_plot(ax, xz, yz)

        r = row["r_pearson"]
        wd = row["WD_z_new"]
        ci_low = row["WD_z_CI_low"]
        ci_high = row["WD_z_CI_high"]

        # Add a compact title above each density plot
        ax.set_title(
            f"{axis_name} | {formato} | {scale_display}\n"
            f"r={r:.2f}".replace("0.", ".")
            + ", "
            + f"WDz={wd:.2f}".replace("0.", ".")
            + " ["
            + f"{ci_low:.2f}".replace("0.", ".")
            + ", "
            + f"{ci_high:.2f}".replace("0.", ".")
            + "]",
            fontsize=10,
            pad=12
        )

        ax.set_xlabel("z-score")
        ax.set_ylabel("Density")

        if i == 0:
            ax.legend(fontsize=9)

    for j in range(len(top_all), len(axes)):
        axes[j].axis("off")

    # Add side labels for the two constructs
    fig.text(
        0.015,
        0.74,
        "DEP",
        fontsize=22,
        fontweight="bold",
        rotation=90,
        va="center"
    )

    fig.text(
        0.015,
        0.28,
        "WOR",
        fontsize=22,
        fontweight="bold",
        rotation=90,
        va="center"
    )

    plt.subplots_adjust(
        left=0.08,
        right=0.98,
        top=0.98,
        bottom=0.06,
        wspace=0.30,
        hspace=0.35
    )

    output_name = f"FIGURE 3_{subset}.tiff"

    plt.savefig(
        output_name,
        dpi=300,
        format="tiff",
        bbox_inches="tight"
    )

    plt.show()

    files.download(output_name)

    print(f"Figure saved as: {output_name}")


# ======================================================
# CREATE THREE SEPARATE IMAGES: ALL, T1, AND T2
# ======================================================
plot_dep_wor_top6_single_image(
    df_scored=df_scored,
    df_wd=df_wd,
    subset="ALL",
    top_n=TOP_N
)

plot_dep_wor_top6_single_image(
    df_scored=df_scored,
    df_wd=df_wd,
    subset="T1",
    top_n=TOP_N
)

plot_dep_wor_top6_single_image(
    df_scored=df_scored,
    df_wd=df_wd,
    subset="T2",
    top_n=TOP_N
)

print("Completed: three separate TIFF images were created.")

# FIGURE 4
# =========================================================
# MTMM FOR ALL, T1, AND T2
# =========================================================

filename = "SemanticAxes.xlsx"

df_scored = pd.read_excel(
    filename,
    sheet_name="Dati_Scoring_Semantic"
)

print("Number of rows:", len(df_scored))


# =========================================================
# PARAMETERS
# =========================================================

AXIS_ORDER = [
    "DEP_CESD",
    "DEP_ZUNG",
    "DEP_WORDS",
    "WOR_STAI",
    "WOR_ZUNG",
    "WOR_WORDS"
]

FORMAT_ORDER = [
    "Select words",
    "Write words",
    "Write phrases",
    "Write text (Mean)",
    "Write text (Max Abs)",
    "Write text"
]

FORMAT_ORDER_FIGURE = [
    "Select words",
    "Write words",
    "Write phrases",
    "Write text",
    "Write text (Max Abs)",
    "Write text (Mean)"
]

FORMAT_TO_INTERNAL = {
    "Write text (Mean)": "Text_Mean",
    "Write text (Max Abs)": "Text_MaxAbs",
    "Write text": "Text_Std",
    "Write words": "Word_Std",
    "Write phrases": "Phrase_Std",
    "Select words": "Select_Std",
}


# =========================================================
# IDENTIFY AI SCORE COLUMNS
# =========================================================

def infer_trait(axis_name):
    axis_name = str(axis_name)

    if axis_name.startswith("DEP"):
        return "DEP"

    if axis_name.startswith("WOR"):
        return "WOR"

    return "OTHER"


def extract_method_info(colname):

    if "__" not in colname:
        return None

    axis = colname.split("__")[0]
    internal = colname.split("__")[1]

    matched_format = None

    for fmt, internal_suffix in FORMAT_TO_INTERNAL.items():
        if internal.endswith(internal_suffix):
            matched_format = fmt
            break

    if matched_format is None:
        return None

    return {
        "Column": colname,
        "Axis": axis,
        "Trait": infer_trait(axis),
        "Formato": matched_format,
        "Label": f"{axis} | {matched_format}"
    }


score_cols = []

for c in df_scored.columns:
    info = extract_method_info(c)

    if info is not None:
        score_cols.append(info)

df_methods = pd.DataFrame(score_cols)

df_methods["Axis_Order"] = df_methods["Axis"].apply(
    lambda x: AXIS_ORDER.index(x) if x in AXIS_ORDER else 999
)

df_methods["Formato_Order"] = df_methods["Formato"].apply(
    lambda x: FORMAT_ORDER.index(x) if x in FORMAT_ORDER else 999
)

df_methods = df_methods.sort_values(
    ["Axis_Order", "Formato_Order"]
).reset_index(drop=True)


# =========================================================
# FUNCTIONS
# =========================================================

def wrap_axis_label(label):
    return label.replace("_", "\n")


def make_format_specific_matrix(df_data, df_methods, formato):

    df_fmt = df_methods[df_methods["Formato"] == formato].copy()

    if df_fmt.empty:
        return pd.DataFrame()

    df_fmt = df_fmt.sort_values("Axis_Order").reset_index(drop=True)

    labels = df_fmt["Axis"].tolist()
    cols = df_fmt["Column"].tolist()

    mat = pd.DataFrame(
        np.nan,
        index=labels,
        columns=labels
    )

    for i in range(len(df_fmt)):
        for j in range(len(df_fmt)):

            c1 = cols[i]
            c2 = cols[j]

            x = pd.to_numeric(df_data[c1], errors="coerce")
            y = pd.to_numeric(df_data[c2], errors="coerce")

            mask = x.notna() & y.notna()

            if mask.sum() < 3:
                continue

            mat.iloc[i, j] = np.corrcoef(x[mask], y[mask])[0, 1]

    return mat


def make_all_format_matrices(df_data, df_methods):

    format_matrices = {}

    for formato in FORMAT_ORDER_FIGURE:

        mat = make_format_specific_matrix(
            df_data=df_data,
            df_methods=df_methods,
            formato=formato
        )

        if not mat.empty:
            format_matrices[formato] = mat

    return format_matrices


def plot_six_matrices_in_one_figure(
    format_matrices,
    output_tiff,
    figure_title=None
):

    # =========================================================
    # SINGLE PLOT: 6 MATRICES IN ONE FIGURE
    # =========================================================

    fig, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(24, 14)
    )

    axes = axes.flatten()

    vmin = 0
    vmax = 1

    last_im = None

    for ax, formato in zip(axes, FORMAT_ORDER_FIGURE):

        mat = format_matrices.get(formato)

        if mat is None or mat.empty:
            ax.axis("off")
            continue

        data = mat.values.astype(float)

        labels = mat.index.tolist()
        wrapped_labels = [wrap_axis_label(l) for l in labels]

        im = ax.imshow(
            data,
            aspect="auto",
            vmin=vmin,
            vmax=vmax,
            cmap="Blues"
        )

        last_im = im

        ax.set_xticks(np.arange(len(labels)))
        ax.set_yticks(np.arange(len(labels)))

        ax.set_xticklabels(
            wrapped_labels,
            rotation=0,
            fontsize=9,
            ha="center"
        )

        ax.set_yticklabels(
            wrapped_labels,
            fontsize=9
        )

        # =====================================================
        # DISPLAY LARGER VALUES INSIDE THE CELLS
        # =====================================================

        for i in range(data.shape[0]):
            for j in range(data.shape[1]):

                val = data[i, j]

                if not np.isnan(val):

                    ax.text(
                        j,
                        i,
                        f"{val:.2f}".replace("0.", "."),
                        ha="center",
                        va="center",
                        fontsize=15
                    )

        # =====================================================
        # DEP/WOR SEPARATOR
        # =====================================================

        traits = [
            "DEP" if l.startswith("DEP")
            else "WOR" if l.startswith("WOR")
            else "OTHER"
            for l in labels
        ]

        for i in range(1, len(traits)):

            if traits[i] != traits[i - 1]:

                ax.axhline(
                    i - 0.5,
                    color="white",
                    linewidth=2.5
                )

                ax.axvline(
                    i - 0.5,
                    color="white",
                    linewidth=2.5
                )

        ax.set_title(
            formato,
            fontsize=15,
            fontweight="bold",
            pad=12
        )

    # =========================================================
    # COLORBAR
    # =========================================================

    plt.subplots_adjust(
        right=0.88,
        wspace=0.30,
        hspace=0.30
    )

    if last_im is not None:

        cbar_ax = fig.add_axes([0.91, 0.15, 0.02, 0.7])

        cbar = fig.colorbar(
            last_im,
            cax=cbar_ax
        )

        cbar.set_label(
            "Pearson correlation",
            fontsize=13
        )

        cbar.ax.tick_params(labelsize=11)

    # =========================================================
    # SAVE TIFF FILE
    # =========================================================

    plt.savefig(
        output_tiff,
        dpi=300,
        format="tiff",
        bbox_inches="tight"
    )

    plt.show()

    print(f"Combined figure saved as: {output_tiff}")


# =========================================================
# CREATE: ALL
# =========================================================

format_matrices_all = make_all_format_matrices(
    df_data=df_scored,
    df_methods=df_methods
)

plot_six_matrices_in_one_figure(
    format_matrices=format_matrices_all,
    output_tiff="FIGURE 4.tiff"
)


# =========================================================
# CREATE: T1
# =========================================================

df_t1 = df_scored[df_scored["Time"] == "T1"].copy()

format_matrices_t1 = make_all_format_matrices(
    df_data=df_t1,
    df_methods=df_methods
)

plot_six_matrices_in_one_figure(
    format_matrices=format_matrices_t1,
    output_tiff="FIGURE 4_T1.tiff",
    figure_title=None
)


# =========================================================
# CREATE: T2
# =========================================================

df_t2 = df_scored[df_scored["Time"] == "T2"].copy()

format_matrices_t2 = make_all_format_matrices(
    df_data=df_t2,
    df_methods=df_methods
)

plot_six_matrices_in_one_figure(
    format_matrices=format_matrices_t2,
    output_tiff="FIGURE 4_T2.tiff",
    figure_title=None
)


# =========================================================
# DOWNLOAD FIGURES
# =========================================================

files.download("FIGURE 4.tiff")
files.download("FIGURE 4_T1.tiff")
files.download("FIGURE 4_T2.tiff")

print("Completed: three TIFF figures were created, each containing six matrices.")

# FIGURE 5

sent = pd.read_excel(
    "Sentiment_Analysis_Benchmark.xlsx",
    sheet_name="CrossSectional"
)

proj = pd.read_excel(
    "SemanticAxes.xlsx",
    sheet_name="Semantic_CrossSectional"
)

# =========================================================
# 2. FILTER SUBSET
# =========================================================
subset_to_use = "ALL"

sent = sent[sent["Subset"] == subset_to_use].copy()
proj = proj[proj["Subset"] == subset_to_use].copy()

# =========================================================
# 3. CREATE DOMAIN FROM AXIS NAMES
# =========================================================
def axis_to_domain(axis_name):
    axis_name = str(axis_name)

    if axis_name.startswith("DEP"):
        return "DEPRESSION"
    elif axis_name.startswith("WOR"):
        return "WORRY"
    else:
        return np.nan

proj["Domain"] = proj["Axis"].apply(axis_to_domain)

# =========================================================
# 4. RENAME CORRELATION COLUMNS
# =========================================================
sent = sent.rename(columns={"r_disattenuated_partial": "sent_r"})
proj = proj.rename(columns={"r_disattenuated_partial": "proj_r"})

# =========================================================
# 5. KEEP ONLY RELEVANT COLUMNS
# =========================================================
sent = sent[["Subset", "Formato", "Domain", "Scala", "sent_r"]].copy()
proj = proj[["Subset", "Axis", "Formato", "Scala", "Domain", "proj_r"]].copy()

# =========================================================
# 6. NORMALIZE FORMAT LABELS
# =========================================================
def normalize_format(x):
    x = str(x).strip()
    x = " ".join(x.split())
    return x

sent["Formato"] = sent["Formato"].apply(normalize_format)
proj["Formato"] = proj["Formato"].apply(normalize_format)

# =========================================================
# 7. MERGE VADER AND SEMANTIC PROJECTION RESULTS
# =========================================================
df = pd.merge(
    proj,
    sent,
    on=["Subset", "Domain", "Formato", "Scala"],
    how="inner"
)

# =========================================================
# 8. DEFINE FORMAT ORDER
# =========================================================
all_formats = [
    "Select words",
    "Write words",
    "Write phrases",
    "Write text",
    "Write text (Mean)",
    "Write text (Max Abs)"
]

plot_formats = [
    "Select words",
    "Write words",
    "Write phrases",
    "Write text"
]

text_projection_formats = [
    "Write text",
    "Write text (Mean)",
    "Write text (Max Abs)"
]

df = df[df["Formato"].isin(all_formats)].copy()

# =========================================================
# 9. DEFINE WITHIN-DOMAIN CLINICAL SCALES
# =========================================================
domain_scales = {
    "DEPRESSION": ["PHQtot", "CESDtot"],
    "WORRY": ["GADtot", "PSWQtot"]
}

# =========================================================
# 10. CREATE INTERNAL SUMMARY TABLE
# =========================================================
summary_rows = []

for domain, scales in domain_scales.items():
    for scale in scales:

        for fmt in ["Select words", "Write words", "Write phrases"]:
            sub = df[
                (df["Domain"] == domain) &
                (df["Scala"] == scale) &
                (df["Formato"] == fmt)
            ].copy()

            if sub.empty:
                continue

            best_idx = sub["proj_r"].idxmax()

            summary_rows.append({
                "Domain": domain,
                "Scala": scale,
                "Formato": fmt,
                "VADER": sub["sent_r"].iloc[0],
                "Projection": sub.loc[best_idx, "proj_r"],
                "Best_Axis": sub.loc[best_idx, "Axis"],
                "Projection_Source_Format": sub.loc[best_idx, "Formato"],
                "Delta": sub.loc[best_idx, "proj_r"] - sub["sent_r"].iloc[0]
            })

        sub_proj_text = df[
            (df["Domain"] == domain) &
            (df["Scala"] == scale) &
            (df["Formato"].isin(text_projection_formats))
        ].copy()

        sub_vader_text = df[
            (df["Domain"] == domain) &
            (df["Scala"] == scale) &
            (df["Formato"] == "Write text")
        ].copy()

        if (not sub_proj_text.empty) and (not sub_vader_text.empty):
            best_idx = sub_proj_text["proj_r"].idxmax()

            summary_rows.append({
                "Domain": domain,
                "Scala": scale,
                "Formato": "Write text",
                "VADER": sub_vader_text["sent_r"].iloc[0],
                "Projection": sub_proj_text.loc[best_idx, "proj_r"],
                "Best_Axis": sub_proj_text.loc[best_idx, "Axis"],
                "Projection_Source_Format": sub_proj_text.loc[best_idx, "Formato"],
                "Delta": sub_proj_text.loc[best_idx, "proj_r"] - sub_vader_text["sent_r"].iloc[0]
            })

df_summary = pd.DataFrame(summary_rows)

df_summary["Formato"] = pd.Categorical(
    df_summary["Formato"],
    categories=plot_formats,
    ordered=True
)

df_summary = df_summary.sort_values(
    ["Domain", "Scala", "Formato"]
).reset_index(drop=True)


def clean_scale_label(scale):
    return str(scale).replace("tot", "")


def plot_delta_all_scales(summary_df, save_path=None):
    plt.figure(figsize=(12, 6))

    line_order = [
        ("DEPRESSION", "PHQtot"),
        ("DEPRESSION", "CESDtot"),
        ("WORRY", "GADtot"),
        ("WORRY", "PSWQtot")
    ]

    for domain, scale in line_order:
        sub = summary_df[
            (summary_df["Domain"] == domain) &
            (summary_df["Scala"] == scale)
        ].copy()

        if sub.empty:
            continue

        sub = sub.sort_values("Formato")

        linestyle = "-" if domain == "DEPRESSION" else "--"

        plt.plot(
            sub["Formato"],
            sub["Delta"],
            marker="o",
            linewidth=2,
            linestyle=linestyle,
            label=f"{domain} - {clean_scale_label(scale)}"
        )

    plt.axhline(0, linestyle="--", linewidth=1)

    plt.ylabel("Δ")
    plt.xlabel("Format")

    plt.xticks(rotation=0)
    plt.legend()
    plt.tight_layout()

    if save_path:
        plt.savefig(
            save_path,
            dpi=300,
            format="tiff",
            bbox_inches="tight"
        )

    plt.show()


plot_delta_all_scales(
    df_summary,
    save_path="FIGURE 5.tiff"
)

print("Figure saved as: FIGURE 5.tiff")

# =========================================================
# TABLES 1–3
# Semantic projection associations and split-half reliability
# =========================================================

# =========================================================
# LOAD DATA
# =========================================================
input_file = "SemanticAxes.xlsx"

df_all = pd.read_excel(
    input_file,
    sheet_name="Semantic_CrossSectional"
)

df_all = df_all[df_all["Subset"] == "ALL"].copy()


# =========================================================
# GENERAL PARAMETERS
# =========================================================
ROW_ORDER = [
    "Select words",
    "Write phrases",
    "Write words",
    "Write text",
    "Write text (Max Abs)",
    "Write text (Mean)"
]

SIGNIFICANCE_LEVELS = [
    (0.001, "***"),
    (0.01, "**"),
    (0.05, "*")
]


# =========================================================
# HELPER FUNCTIONS
# =========================================================
def format_correlation_value(r, p):
    stars = ""

    for threshold, symbol in SIGNIFICANCE_LEVELS:
        if p < threshold:
            stars = symbol
            break

    return f"{r:.2f}".replace("0.", ".") + stars


def format_decimal_value(x):
    if pd.isna(x):
        return ""

    return f"{x:.2f}".replace("0.", ".")


def create_association_table(
    df,
    axes,
    scales,
    scale_labels,
    column_order,
    display_columns
):
    temp = df[
        (df["Axis"].isin(axes)) &
        (df["Scala"].isin(scales))
    ].copy()

    temp["Cell"] = temp.apply(
        lambda row: format_correlation_value(
            row["r_disattenuated_partial"],
            row["p_value_analytical"]
        ),
        axis=1
    )

    temp["Column"] = (
        temp["Scala"].replace(scale_labels)
        + "_"
        + temp["Axis"]
    )

    table = temp.pivot_table(
        index="Formato",
        columns="Column",
        values="Cell",
        aggfunc="first"
    )

    table = table.reindex(ROW_ORDER)
    table = table[column_order]
    table.columns = display_columns

    return table


def create_split_half_table(df):
    temp = df[
        [
            "Formato",
            "Axis",
            "reliability_projection_splithalf"
        ]
    ].copy()

    temp["Cell"] = temp["reliability_projection_splithalf"].apply(
        format_decimal_value
    )

    table = temp.pivot_table(
        index="Formato",
        columns="Axis",
        values="Cell",
        aggfunc="first"
    )

    table = table.reindex(ROW_ORDER)

    column_order = [
        "DEP_CESD",
        "DEP_WORDS",
        "DEP_ZUNG",
        "WOR_STAI",
        "WOR_WORDS",
        "WOR_ZUNG"
    ]

    table = table[column_order]

    return table


def print_table(title_lines, table):
    print("\n" + title_lines[0])

    for line in title_lines[1:]:
        print(line)

    print()
    print(table.to_string())


# =========================================================
# TABLE 1: DEPRESSION
# =========================================================
table1 = create_association_table(
    df=df_all,
    axes=["DEP_CESD", "DEP_WORDS", "DEP_ZUNG"],
    scales=["CESDtot", "PHQtot"],
    scale_labels={
        "CESDtot": "CESD",
        "PHQtot": "PHQ"
    },
    column_order=[
        "CESD_DEP_CESD",
        "CESD_DEP_WORDS",
        "CESD_DEP_ZUNG",
        "PHQ_DEP_CESD",
        "PHQ_DEP_WORDS",
        "PHQ_DEP_ZUNG"
    ],
    display_columns=[
        "DEP_CESD",
        "DEP_WORDS",
        "DEP_ZUNG",
        "DEP_CESD",
        "DEP_WORDS",
        "DEP_ZUNG"
    ]
)

print_table(
    [
        "Table 1. Associations between text-derived semantic projections",
        "and depressive symptom measures (CESD and PHQ)",
        "across response formats."
    ],
    table1
)


# =========================================================
# TABLE 2: ANXIETY / WORRY
# =========================================================
table2 = create_association_table(
    df=df_all,
    axes=["WOR_STAI", "WOR_WORDS", "WOR_ZUNG"],
    scales=["GADtot", "PSWQtot"],
    scale_labels={
        "GADtot": "GAD",
        "PSWQtot": "PSWQ"
    },
    column_order=[
        "GAD_WOR_STAI",
        "GAD_WOR_WORDS",
        "GAD_WOR_ZUNG",
        "PSWQ_WOR_STAI",
        "PSWQ_WOR_WORDS",
        "PSWQ_WOR_ZUNG"
    ],
    display_columns=[
        "WOR_STAI",
        "WOR_WORDS",
        "WOR_ZUNG",
        "WOR_STAI",
        "WOR_WORDS",
        "WOR_ZUNG"
    ]
)

print_table(
    [
        "Table 2. Associations between text-derived semantic projections",
        "and anxiety and worry measures (GAD and PSWQ)",
        "across response formats."
    ],
    table2
)


# =========================================================
# TABLE 3: SPLIT-HALF RELIABILITY
# =========================================================
table3 = create_split_half_table(df_all)

print_table(
    [
        "Table 3. Split-half reliability of semantic projection scores",
        "across response formats."
    ],
    table3
)


# =========================================================
# EXPORT TABLES
# =========================================================
output_file = "Semantic_Tables_1_2_3.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    table1.to_excel(writer, sheet_name="Table1")
    table2.to_excel(writer, sheet_name="Table2")
    table3.to_excel(writer, sheet_name="Table3")

print(f"\nAll tables saved as: {output_file}")